### ISSUE TITLE
Not getting all my wallets

### ISSUE THREAD

**Issue by johnbailon** [BitGo/bitgo-cli#6]
bitgo-cli is not giving me access to all my wallets.
`bitgo wallets` produces an incomplete list and `bitgo wallet <addr>` says the wallet is not found.

Could be because I have an enterprise accoun. Although some of my enterprise wallets appear on the list, so not sure if that's the reason and older enterprise wallets just behave differently or I'm missing something.

Any pointers?

**Comment by bencxr** [comment]
Hey John, how many wallets do you have?
bitgo-cli is not designed for use with more than 500 wallets.

**Comment by johnbailon** [comment]
@bencxr, I see. That could be it. I guess the best way to do this is to allow something like this: 
`$ bitgo wallets --enterprise <enterprise_id>`
 What do you think?

**Comment by bencxr** [comment]
That wouldn't lower the limit though. 
If you have many wallets, it may take simply too long to allow such a query. What are you trying ot achieve by viewing these? Getting balances?

**Comment by johnbailon** [comment]
It could work for my case since I have lesser wallets in my enterprise account. Maybe another solution would be to allow a direct `$ bitgo wallet <addr>` work even if the wallet was not part of the `$ bitgo wallets` return?

I'm trying to retrieve the comments part which isn't documented in the [docs](https://www.bitgo.com/api/) for auditing purposes. I see it though at endpoint `api/v1/wallet/<addr>/wallettx?skip=0&limit=500`. I may as well just use thatm but its just a lot easier to redirect results into a json file like this: `$ bitgo -j tx >> transactions.json` though so I thought someone else might benefit a fix like this?

**Comment by bpdavenport** [comment]
Hi John,

Have you looked at the CSV reports available in the web interface? They
allow exporting of all transactions on a wallet, with comments.

Ben

**Comment by johnbailon** [comment]
@bpdavenport ah, yes.  We can use that. Wanted to somehow automate it, but those reports will do for now. Thanks!

**Comment by bpdavenport** [comment]
You can automate downloading the CSV. Everything our web client does is via
API. It's not documented, but the call is very easy:

https://www.bitgo.com/api/v1/reports/<walletid>?format=csv&period=all

Ben

**Comment by johnbailon** [comment]
This is great! Thanks for this, @bpdavenport.
